# Generated by Django 5.2.1 on 2025-05-27 17:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hecatemarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicalitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
