# Generated by Django 5.2.1 on 2025-05-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecatemarket', '0002_alter_magicalitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_items/'),
        ),
    ]
