# Generated by Django 4.2.16 on 2025-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthchartrequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dreamsubmission',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mediumcontactrequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ritualrequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='witchquestion',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='birthchartrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dreamsubmission',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='mediumcontactrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ritualrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='witchquestion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
